name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-jssdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: npm
      - run: npm install
      - run: npm run compile
      - run: npx @phala/fn build
      - run: "npx @phala/fn run dist/index.js -a 0x0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000de1683287529b9b4c3132af8aad210644b259cfd '{\"apiUrl\": \"https://gateway.thegraph.com/api/\", \"apiKey\": \"cd22a01e5b7f9828cddcb52caf03ee79\"}'"
